apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello world"

---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  tasks:
    - name: echo-hello-world
      taskRef:
        name: echo-hello-world