apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: helloworld-pipelinerun
spec:
  pipelineRef:
    name: helloworld-pipeline
  serviceAccount: 'default'
  # resources:
  #   - name: builtImage
  #     resourceRef: 
  #       name: cb-core-image